astrophotography/urls.py
from django.urls import path

from astrophotography.views import *

app_name = 'astrophotography'
urlpatterns = [
    path('upload/', ImageUploadView.as_view(), name='upload-image'),
    path('gallery/', PublicImageGalleryView.as_view(), name='gallery')
]

core/urls.py
from django.urls import path

from core.views import *

app_name = 'core'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('join/', FleetRegistrationView.as_view(), name='join'),
    path('fleet/roster/', RosterView.as_view(), name='roster'),
    path('fleet/stats/', FleetStatsView.as_view(), name='stats'),
    path('fleet/showcase/', FleetShowcaseView.as_view(), name='showcase'),
    path('expedition/distantworlds2/', DistantWorlds2View.as_view(), name='distantworlds2'),
    path('expedition/cg-proposal/', CGProposalView.as_view(), name='cg-proposal'),
    path('expedition/background/', BackgroundView.as_view(), name='background'),
    path('info/contact/', ContactView.as_view(), name='contact'),
    path('info/privategroups/', PrivateGroupsView.as_view(), name='privategroups'),
    path('info/order/', OrderView.as_view(), name='order'),
    path('info/faq/',  FAQView.as_view(), name='faq'),
    path('info/assets/',  AssetsView.as_view(), name='assets'),
    path('scouting/', ScoutingView.as_view(), name='scouting'),
    path('expedition/logistics/', LogisticsView.as_view(), name='logistics'),

    path('ajax/roster', RosterDataJSON, name='roster_ajax'),
    path('success/', Success.as_view(), name='success'),
]

distantworlds2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core.views import SignUpView

urlpatterns = [
    # auth
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', SignUpView.as_view(), name='register'),

    path('', include('core.urls')),
    path('', include('news.urls')),
    path('photos/', include('astrophotography.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path

from news.views import *

app_name = 'news'
urlpatterns = [
    path('news/', NewsView.as_view(), name='news'),
]

core/models.py
from pprint import pprint

import dateutil.parser
import gspread
from dateutil import tz
from django.contrib.auth.models import User
from django.db import models
from django.db.utils import IntegrityError
from djchoices import DjangoChoices, ChoiceItem
from oauth2client.service_account import ServiceAccountCredentials
from tqdm import tqdm

from distantworlds2.settings.base import SITE_ROOT  # to ensure correct opening of client secret


class Location(models.Model):
    # system
    system = models.CharField(max_length=128, null=False, blank=False)
    x = models.FloatField(null=True)
    y = models.FloatField(null=True)
    z = models.FloatField(null=True)

    # body
    body = models.CharField(max_length=64, null=True, blank=True)
    gravity = models.FloatField(null=True, blank=True)

    # surface
    site_name = models.CharField(max_length=128, null=True, blank=True)
    lat = models.FloatField(null=True, blank=True)
    lon = models.FloatField(null=True, blank=True)

    # edsm
    edsm_id = models.IntegerField(null=True)  # system id

    # todo: integrate with edsm

    def __str__(self):
        s = ['{system}'.format(system=self.system)]
        if self.body:
            s.append('{body}'.format(body=self.body))
        if self.lat and self.lon:
            s.append('[{lat:.4f}/{lon:.4f}]'.format(lat=self.lat, lon=self.lon))
        return str.join(' ', s)

    def get_absolute_url(self):
        pass  # todo


class Waypoint(models.Model):
    id = models.IntegerField(primary_key=True)          # waypoint number
    name = models.CharField(max_length=128)             # waypoint name
    # base_camp_name = models.CharField(max_length=128)   # base camp name stored in base_camp.site_name

    # todo: defaults - if upload date is before or on arrival date, sort into this waypoint folder
    arrival_date = models.DateField()
    base_camp = models.ForeignKey(Location, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return "Waypoint {:02d}: {}".format(self.id, self.base_camp.site_name)

    @property
    def abbrev(self):
        if self.id == 0:
            return "Pre-Expedition"
        elif self.id == -1:
            return "Post-Expedition"
        else:
            return "WP{:02d}".format(self.id)


class Commander(models.Model):

    class Role(DjangoChoices):
        explorer = ChoiceItem(0, 'Explorer')
        fuel_rat = ChoiceItem(1, 'Fuel Rat')
        miner = ChoiceItem(2, 'Miner')
        mechanic = ChoiceItem(3, 'Fleet Mechanic')
        guide = ChoiceItem(4, 'Tour Guide')
        photo = ChoiceItem(5, 'Photographer')
        escort = ChoiceItem(6, 'Fighter Escort')
        geologist = ChoiceItem(7, 'Geologist')
        scientist = ChoiceItem(8, 'Scientist')
        media = ChoiceItem(9, 'Media')
        medicorp = ChoiceItem(10, 'MediCorp')
        logistics = ChoiceItem(11, 'Fleet Logistics')

    class Platform(DjangoChoices):
        pc = ChoiceItem('PC', 'PC')
        xbox = ChoiceItem('XBOne', 'Xbox One')
        ps4 = ChoiceItem('PS4', 'PlayStation 4')
        mac = ChoiceItem('Mac', 'Mac')

    class Ship(DjangoChoices):
        adder = ChoiceItem('adder', 'Adder')
        conda = ChoiceItem('conda', 'Anaconda')
        aspx = ChoiceItem('aspx', 'Asp Explorer')
        asps = ChoiceItem('asps', 'Asp Scout')
        beluga = ChoiceItem('beluga', 'Beluga')
        chieftain = ChoiceItem('chieftain', 'Alliance Chieftain')
        cobra3 = ChoiceItem('cobra3', 'Cobra Mk. III')
        cobra4 = ChoiceItem('cobra4', 'Cobra Mk. IV')
        dbx = ChoiceItem('dbx', 'Diamondback Explorer')
        dbs = ChoiceItem('dbs', 'Diamondback Scout')
        dolphin = ChoiceItem('dolphin', 'Dolphin')
        eagle = ChoiceItem('eagle', 'Eagle')
        fas = ChoiceItem('fas', 'Federal Assault Ship')
        corvette = ChoiceItem('corvette', 'Federal Corvette')
        dropship = ChoiceItem('dropship', 'Federal Dropship')
        gunship = ChoiceItem('gunship', 'Federal Gunship')
        fdl = ChoiceItem('fdl', 'Fer-De-Lance')
        hauler = ChoiceItem('hauler', 'Hauler')
        clipper = ChoiceItem('clipper', 'Imperial Clipper')
        courier = ChoiceItem('courier', 'Imperial Courier')
        cutter = ChoiceItem('cutter', 'Imperial Cutter')
        ieagle = ChoiceItem('ieagle', 'Imperial Eagle')
        keelback = ChoiceItem('keelback', 'Keelback')
        krait = ChoiceItem('krait', 'Krait')
        orca = ChoiceItem('orca', 'Orca')
        python = ChoiceItem('python', 'Python')
        sidewinder = ChoiceItem('sidewinder', 'Sidewinder')
        t10 = ChoiceItem('t10', 'Type-10 Defender')
        t6 = ChoiceItem('t6', 'Type-6 Transporter')
        t7 = ChoiceItem('t7', 'Type-7 Transporter')
        t9 = ChoiceItem('t9', 'Type-9 Heavy')
        viper3 = ChoiceItem('viper3', 'Viper Mk. III')
        viper4 = ChoiceItem('viper4', 'Viper Mk. IV')
        vulture = ChoiceItem('vulture', 'Vulture')

    # application number (pk)
    app_num = models.PositiveIntegerField('App. #', primary_key=True)

    # relationship
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True)

    # commander info
    cmdr_name = models.CharField('Commander Name', max_length=25)

    # distant worlds 2 info (see roster)
    roster_num = models.PositiveSmallIntegerField('DW2 Roster #', unique=True)

    staff = models.BooleanField('Expedition staff', default=False)

    modified = models.DateTimeField()

    ship_model = models.CharField('Ship Model', max_length=16, choices=Ship.choices)
    ship_name = models.CharField('Ship Name', max_length=24, null=True, blank=True)
    call_sign = models.CharField('Ship ID', max_length=6)
    ship_range = models.FloatField('Jump Range (LY)')
    ship_showcase_link = models.CharField('Showcase Image Link', max_length=256, null=True, blank=True)
    livery = models.CharField('ship livery', max_length=48, null=True)
    comms_id = models.CharField('Comms Nickname', max_length=15, null=True)
    timezone = models.CharField('Timezone', max_length=8, null=True)
    platform = models.CharField('Platform', max_length=8, choices=Platform.choices, default=Platform.pc)
    dwe_veteran = models.BooleanField('Participated in DWE 3302', default=False)
    visited_beagle_point = models.BooleanField('Has visited Beagle Point', default=False)

    role1 = models.IntegerField('Primary Role', choices=Role.choices, default=Role.explorer)
    role2 = models.IntegerField('Secondary Role', choices=Role.choices, null=True)

    avg_playtime = models.CharField('Average hours played per week', max_length=16)

    # region expeditions
    exp_01 = models.BooleanField('Expedition: Nebulae Research Voyages', default=False)
    exp_02 = models.BooleanField('Expedition: REGOR Border Mapping', default=False)
    exp_03 = models.BooleanField('Expedition: Sagittarius-Carina Mission', default=False)
    exp_04 = models.BooleanField('Expedition: Dumbbell Project', default=False)
    exp_05 = models.BooleanField('Expedition: Distant Worlds 3302', default=False)
    exp_06 = models.BooleanField('Expedition: Formidine Rift Survey', default=False)
    exp_07 = models.BooleanField('Expedition: Meet & Greet Expedition', default=False)
    exp_08 = models.BooleanField('Expedition: Crab Nebula Expedition', default=False)
    exp_09 = models.BooleanField('Expedition: Borderlands Venture', default=False)
    exp_10 = models.BooleanField('Expedition: Western Expedition', default=False)
    exp_11 = models.BooleanField('Expedition: August Exodus - A Jaunt To Jaques', default=False)
    exp_12 = models.BooleanField('Expedition: Lost Stars - DWE XBox', default=False)
    exp_13 = models.BooleanField('Expedition: Formidine Rift Expedition', default=False)
    exp_14 = models.BooleanField('Expedition: Small Worlds Expedition', default=False)
    exp_15 = models.BooleanField('Expedition: Go West', default=False)
    exp_16 = models.BooleanField('Expedition: Galactic Nebula Expedition', default=False)
    exp_17 = models.BooleanField('Expedition: Colonia Core Circuit 3302', default=False)
    exp_18 = models.BooleanField('Expedition: Cassiopeia Project', default=False)
    exp_19 = models.BooleanField('Expedition: S.H.E.P.A.R.D. Mission', default=False)
    exp_20 = models.BooleanField('Expedition: Christmas Carriers Convoy', default=False)
    exp_21 = models.BooleanField('Expedition: Distant Stars - Unknown Origins', default=False)
    exp_22 = models.BooleanField('Expedition: Meet & Greet Expedition 2', default=False)
    exp_23 = models.BooleanField('Expedition: Heavy Weight Champions Circuit', default=False)
    exp_24 = models.BooleanField('Expedition: La Grande Expédition Remlok', default=False)
    exp_25 = models.BooleanField('Expedition: Mind The Gap', default=False)
    exp_26 = models.BooleanField('Expedition: Silly Ships Expedition', default=False)
    exp_27 = models.BooleanField('Expedition: Pioneers And Explorers', default=False)
    exp_28 = models.BooleanField('Expedition: Mercury 7 Expedition', default=False)
    exp_29 = models.BooleanField('Expedition: Helium Hunt', default=False)
    exp_30 = models.BooleanField("Expedition: Helicon's Peak Expedition", default=False)
    exp_31 = models.BooleanField('Expedition: Local Sightseeing Tour', default=False)
    exp_32 = models.BooleanField('Expedition: Azophi Expedition', default=False)
    exp_33 = models.BooleanField('Expedition: Silly Ships Expedition 2', default=False)
    exp_34 = models.BooleanField('Expedition: Summer Great Expedition', default=False)
    exp_35 = models.BooleanField('Expedition: Small Worlds Expedition 2', default=False)
    exp_36 = models.BooleanField('Expedition: Monoceros Mission', default=False)
    exp_37 = models.BooleanField('Expedition: Land Of Giants', default=False)
    exp_38 = models.BooleanField('Expedition: Grand Day Out', default=False)
    exp_39 = models.BooleanField('Expedition: Devos Expedition Program #1', default=False)

news/models.py
# Create your models here.

core/views.py
from django.contrib.auth import login, authenticate
from django.db.models import Count
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views import generic

from core.forms import *


class HomeView(generic.TemplateView):
    template_name = 'core/home.html'


class DistantWorlds2View(generic.TemplateView):
    template_name = 'core/distant-worlds-2.html'


class CGProposalView(generic.TemplateView):
    template_name = 'core/cg_proposal.html'


class FleetRegistrationView(generic.TemplateView):
    template_name = 'core/fleet_registration.html'


class BackgroundView(generic.TemplateView):
    template_name = 'core/background.html'


class PrivateGroupsView(generic.TemplateView):
    template_name = 'core/privategroups.html'


class OrderView(generic.TemplateView):
    template_name = 'core/order.html'


class RosterView(generic.TemplateView):
    template_name = 'core/roster.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['timestamp'] = Commander.objects.latest('modified').modified
        context['commanders'] = Commander.objects.all()
        return context


class FAQView(generic.TemplateView):
    template_name = 'core/faq.html'


class AssetsView(generic.TemplateView):
    template_name = 'core/assets.html'


class ScoutingView(generic.TemplateView):
    template_name = 'core/scouting.html'


class LogisticsView(generic.TemplateView):
    template_name = 'core/logistics.html'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['timestamp'] = Commander.objects.latest('modified').modified
        context['commanders'] = Commander.objects.all()
        return context


class FleetStatsView(generic.TemplateView):
    template_name = 'core/fleet_stats.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        ship_qset = Commander.objects\
            .exclude(ship_model='INVALID SHIP')\
            .values('ship_model')\
            .order_by('ship_model')\
            .annotate(n=Count('ship_model'))
        total_cmdrs = Commander.objects.exclude(ship_model='INVALID SHIP').count()

        # format ship type stats into javascript array (use |safe filter in template)
        context['ship_types'] = [{'ship': Commander.Ship.values.get(s['ship_model']),
                                  'num': s['n'],
                                  'percent': (s['n']/total_cmdrs)} for s in ship_qset]

        return context


class FleetShowcaseView(generic.TemplateView):
    template_name = 'core/showcase.html'


class ContactView(generic.TemplateView):
    template_name = 'core/contact.html'


class SignUpView(generic.FormView):
    # todo: https://simpleisbetterthancomplex.com/article/2017/08/19/how-to-render-django-form-manually.html#rendering-bootstrap-4-forms
    template_name = 'registration/register_form.html'
    success_url = '/success/'

    # return empty form
    def get(self, request, *args, **kwargs):
        user_form = UserForm(prefix='user')
        cmdr_form = CommanderForm(prefix='cmdr')
        return render(request, self.template_name, {'user_form': user_form, 'cmdr_form': cmdr_form})

    # process submitted form
    def post(self, request, *args, **kwargs):
        # process user portion of form
        user_form = UserForm(request.POST, prefix='user')
        cmdr_form = CommanderForm(request.POST, prefix='cmdr')  # created here in case user_form fails validation
        if user_form.is_valid() and cmdr_form.is_valid():  # validate
            # signal receiver creates and links a new Commander object on user_form.save(). The cmdr_form is
            # re-initialized with an instance of user.commander and its data is saved to that object.
            user = user_form.save()
            user.save()

            try:
                cmdr = Commander.objects.get(roster_num=cmdr_form.cleaned_data['roster_num'])
            except Commander.DoesNotExist:
                # todo: redirect to Register Commander form (need to create)
                cmdr = CommanderForm(request.POST, prefix='cmdr').save()  # , instance=user.commander)

            cmdr.user = user
            cmdr.save()

            # authenticate
            raw_pw = user_form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_pw)
            login(request, user)
            return redirect(self.success_url)

        # if both forms are not valid, drop out of if clause and re-render form with errors
        return render(request, self.template_name, {'user_form': user_form, 'cmdr_form': cmdr_form})


# todo: make this better and parse the data and figure out the enums!!!!!!!!!
def RosterDataJSON(request):
    objects = Commander.objects.all().values()
    return JsonResponse({'data': list(objects)})


class Success(generic.TemplateView):
    template_name = 'success.html'

news/views.py
# Create your views here.
from django.views import generic


class NewsView(generic.TemplateView):
    template_name = 'core/news.html'

templates/core/assets.html
	{% extends "base.html" %}

{% block title %}
    Assets
{% endblock %}

{% block content %}
<style type="text/css">
	.btn {
	display: block;
	background-color: #ff7100;
	border: none;
	color: white;
	margin-left: auto;
	margin-right: auto;
	padding: 12px 30px;
	font-size: 18px;
	cursor: pointer;
	font-family: Telegrama;
	font-style: Render;
	}

.btn:hover {
	background-color: #f2c86e;
	color: #000;
	}

a:hover {
	text-decoration: none;
}
</style>
    <div class="title-container">
    	<div class="title-grad"></div>
    <h1 class="h1-std">Distant Worlds 2 Visual Assets</h1>
    <h2 class="h2-std">Official DW2 resources for social media, livestreams and video</h2></div>
    <h3 class="h3-std">Foreword on Intellectual Property</h3>
    <br>
    <p class="p-std">Qohen Leth designed the Distant Worlds 2 logo, from the original 'two-tone' variant of the Distant Worlds 3302 logo by Hi-Ban. The logo contains assets from Frontier Developments, PLC. <span class="warning">You are not authorized to use the logo for profit or in any commercial way.</span> You can use it for non-profit and strict communication purposes, such as (but not limited to): forum avatar, forum signature, livestreams, YouTube videos, narratives, CMDR logs, etc. You are not permitted to transform, crop or subvert it. Please respect the work of the people involved in this community event.</p><br>
    <h3 class="h3-std">Resources pack</h3>
    <br>
    <p class="p-std">Click below to download the .rar archive of Distant Worlds 2 assets. The pack contains:
    	<ul class="ul-std"><li class="li-std"><span style="color: #ff7100;">DW2 logo</span> in: .svg, .png (2000px, 1000px, 500px, 250px, 100px), .pdf</li>
    		<li class="li-std"><span style="color: #f2c86e;">DW2 logo alternate coloring</span> in: .svg, .png (2000px, 1000px, 500px, 250px, 100px), .pdf</li>
    		<li class="li-std">DW2 logo watermark (white) in: .svg, .png (2000px, 1000px, 500px, 250px, 100px)</li>
    		<li class="li-std"><span style="color: #3dabb8;">DW2 text watermark</span> in : .svg, .png (1000px, 500px, 250px)</li>
    		<li class="li-std">Roles icons in: .png (200px, 100px), .gif (200px, 100px)</li>
      	</ul>
    </p>
<a href="https://drive.google.com/open?id=1vC37D0kHtrq7KpTyR1NibcdI_Wh0fu-0"><button class="btn" style="margin-top: 75px; margin-bottom: 25px;"><i class="fa fa-download"></i> DOWNLOAD</button></a>
<div class="row" style="padding-top: 50px; padding-bottom: 50px;">
	<div class="col-sm-6 text-center">
		<img src="/static/svg/dw2patch.svg"><br><br><h4 class="h4-std">Original Logo</h4></div>
	<div class="col-sm-6 text-center">
		<img src="/static/svg/dw2logo_alternate.svg"><br><br><h4 class="h4-std">Alternate Logo</h4></div>
	</div>
<div class="row" style="padding-bottom: 50px;">
	<div class="col-sm-6 text-center">
		<img src="/static/svg/dw2logo_white.svg"><br><br><h4 class="h4-std">White Watermark Logo</h4></div>
	<div class="col-sm-6 text-center align-middle" style="display: flex; flex-direction: column; justify-content: center;">
		<img src="/static/svg/dw2textwatermark.svg" style="width: 100%;"><br><br><h4 class="h4-std">Text Watermark</h4></div>
	</div>



{% endblock %}

templates/core/beginner.html
{% extends "base.html" %}

{% block title %}
    Beginner Guide
{% endblock %}

{% block content %}




{% endblock %}

templates/core/fleet_stats.html
{% extends "base.html" %}

{% block title %}
    Fleet Statistics
{% endblock %}

{% block content %}
    <h1 class="mt-5">fleet statistics</h1>
    <p>these are some fleet statistics</p>
    <script src="//d3js.org/d3.v3.min.js"></script>
    <script>
        var shipTypes = {{ ship_types|safe }};
        for (var i in shipTypes) {
            console.log(shipTypes[i]);
        }
    </script>
{% endblock %}

templates/core/roster.html
{% extends "base.html" %}

{% load static %}
{% block javascript %}
<script src="{% static 'js/table-styler.js' %}"></script>
{% endblock %}

{% block title %}
    Roster
{% endblock %}

{% block content %}
    <h1 class="mt-5 mb-4">distant worlds 2 roster</h1>
    <p>last modified: {{ timestamp }}</p>
    <table id="roster" class="table" style="width:100%">
        <thead>
        <tr>
            <th>Roster #</th>
            <th>Commander</th>
            <th>Comms ID</th>
            <th>Ship Type</th>
            <th>Ship Name</th>
            <th>Jump Range</th>
            <th>Paintjob</th>
            <th>Primary Role</th>
            <th>Secondary Role</th>
            <th>DWE 3302 Veteran</th>
            <th>Visited Beagle Point</th>
            <th>Platform</th>
        </tr>
        </thead>
        <tbody>
        {% for cmdr in commanders %}
            <tr class=" {% if cmdr.staff %}dwe-staff{% endif %}">
                {# todo: change data printing to use ajax instead of pure html #}
                <td>{{ cmdr.roster_num }}</td>
                <td>{{ cmdr.cmdr_name }}</td>
                <td>{{ cmdr.comms_id|default_if_none:"" }}</td>
                <td>{{ cmdr.get_ship_model_display }}</td>
                <td>{{ cmdr.ship_name|default_if_none:"" }}</td>
                <td>{{ cmdr.ship_range }}</td>
                <td>{{ cmdr.livery }}</td>
                <td>{{ cmdr.get_role1_display }}</td>
                <td>{{ cmdr.get_role2_display|default_if_none:"" }}</td>
                <td>{{ cmdr.dwe_veteran }}</td>
                <td>{{ cmdr.visited_beagle_point }}</td>
                <td>{{ cmdr.get_platform_display }}</td>
            </tr>
        {% endfor %}
        {# todo: https://datatables.net/examples/api/multi_filter.html #}
        {# todo: https://datatables.net/examples/api/multi_filter_select.html #}
        </tbody>
        <tfoot>
        <tr>
            <th>Roster #</th>
            <th>Commander</th>
            <th>Comms ID</th>
            <th>Ship Type</th>
            <th>Ship Name</th>
            <th>Jump Range</th>
            <th>Paintjob</th>
            <th>Primary Role</th>
            <th>Secondary Role</th>
            <th>DWE 3302 Veteran</th>
            <th>Visited Beagle Point</th>
            <th>Platform</th>
        </tr>
        </tfoot>
    </table>

    <script>
        $(document).ready(function () {
            $('#roster').DataTable(/*{
                initComplete: function () {
                    this.api().columns().every(function () {
                        var column = this;
                        var select = $('<select><option value=""></option></select>')
                            .appendTo($(column.footer()).empty())
                            .on('change', function () {
                                var val = $.fn.dataTable.util.escapeRegex(
                                    $(this).val()
                                );

                                column
                                    .search(val ? '^' + val + '$' : '', true, false)
                                    .draw();
                            });

                        column.data().unique().sort().each(function (d, j) {
                            select.append('<option value="' + d + '">' + d + '</option>')
                        });
                    });
                }
            }*/);
        });
    </script>

{% endblock %}